[package]
name = "psybeacon-host"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.11"
hostname = "0.4"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_Devices_DeviceAndDriverInstallation", "Win32_Storage_FileSystem", "Win32_System_IO", "Win32_System_Threading", "Win32_System_Diagnostics_ToolHelp", "Win32_System_RemoteDesktop", "Win32_System_Memory", "Win32_System_DataExchange", "Win32_Security", "Win32_System_Registry", "Win32_Graphics_Dxgi", "Win32_Graphics_Dxgi_Common", "Win32_Graphics_Direct3D11", "Win32_Graphics_Direct3D", "Win32_Graphics_Gdi", "Win32_Devices_Display", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging"] }
ctrlc = "3.5.2"
tungstenite = "0.30.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
windows-service = "0.8.1"

[profile.release]
lto = true
